parameters:
    cache_service: itmedia_zippy_bus.cache

services:

    itmedia_zippy_bus.client:
        class: Itmedia\ZippyBusBundle\Client\ZippyBusClient
        arguments:
            - '%itmedia_zippy_bus.token%'
            - '@itmedia_zippy_bus.cache'
            - '%itmedia_zippy_bus.cache_ttl%'
        public: false


    itmedia_zippy_bus.factory:
        class: Itmedia\ZippyBusBundle\Factory\ScheduleObjectFromArrayFactory
        public: false


    itmedia_zippy_bus.provider:
        class: Itmedia\ZippyBusBundle\ZippyBusProvider
        arguments:
            - '@itmedia_zippy_bus.client'
            - '@itmedia_zippy_bus.factory'


    itmedia_zippy_bus.cache:
        class: Symfony\Component\Cache\Simple\PhpFilesCache
        public: false